### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by samwalker191** [JonYu87/Bestflix#1]
Wiki Page Home
- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page
## Comments
---
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
---
# Frontend Routes
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by samwalker191** [comment]
**MVP List Comments:**

- [x] Genre MVP is good as is. The second bullet doesn't need to be in the Search MVP
- [x] A little nitpicky, but make sure there is a space after each number in the list.

**Comment by samwalker191** [comment]
**Schema Comments:**

- [x] You'll need a table for the mylist feature.
- [x] Make sure `created_at` and `updated_at` have underscores.
- [x] One thing to think about, is if a movie should be able to have multiple genres and how would you change your schema to represent that.

**Comment by samwalker191** [comment]
**Sample State Comments:**

- [x] See the checklist above for formatting.

**Comment by JonYu87** [comment]
> **Sample State Comments:**
> 
> * [ ]  See the checklist above for formatting.

Whoops, forgot to add the JS part haha. Fixed, thank you!

**Comment by JonYu87** [comment]
> **MVP List Comments:**
> 
> * [ ]  Genre MVP is good as is. The second bullet doesn't need to be in the Search MVP
> * [ ]  A little nitpicky, but make sure there is a space after each number in the list.

Gotcha! Fixed the spacing! Also, I would love for you to be as nit picky as possible so I can learn!

**Comment by JonYu87** [comment]
> **Schema Comments:**
> 
> * [ ]  You'll need a table for the mylist feature.
> * [ ]  Make sure `created_at` and `updated_at` have underscores.
> * [ ]  One thing to think about, is if a movie should be able to have multiple genres and how would you change your schema to represent that.

Created the table for the MyList, also in terms of a movie having multiple genres, would I just do that through the associations since I have genre_id in my videos table? Or would it actually be better to put a video_id in my Genre table?

**Comment by JonYu87** [comment]
Side note, how should I generally respond to the issues? Do I check them off as I do them then tell you or do you just review them and check them off? Should I reply to each issue or should I just comment down here and let you know that I have addressed the issues. Thanks for all the help so far by the way Walker and thank you in advance for the weeks to come!

**Comment by samwalker191** [comment]
The way that you have commented is perfect!

**Comment by samwalker191** [comment]
> > **Schema Comments:**
> > 
> > * [ ]   You'll need a table for the mylist feature.
> > * [ ]   Make sure `created_at` and `updated_at` have underscores.
> > * [ ]   One thing to think about, is if a movie should be able to have multiple genres and how would you change your schema to represent that.
> 
> Created the table for the MyList, also in terms of a movie having multiple genres, would I just do that through the associations since I have genre_id in my videos table? Or would it actually be better to put a video_id in my Genre table?

For multiple genres, you would need a joins table to represent it. The relationship would be a many-to-many. A genre can have many movies, and a movie can have many genres. So you would actually take out the `genre_id` from the videos table and create a joins table to connect the videos table to the genres table.

**Comment by samwalker191** [comment]
**Backend Routes Comments:**

Looks good!

**Comment by JonYu87** [comment]
> > > **Schema Comments:**
> > > 
> > > * [ ]    You'll need a table for the mylist feature.
> > > * [ ]    Make sure `created_at` and `updated_at` have underscores.
> > > * [ ]    One thing to think about, is if a movie should be able to have multiple genres and how would you change your schema to represent that.
> > 
> > 
> > Created the table for the MyList, also in terms of a movie having multiple genres, would I just do that through the associations since I have genre_id in my videos table? Or would it actually be better to put a video_id in my Genre table?
> 
> For multiple genres, you would need a joins table to represent it. The relationship would be a many-to-many. A genre can have many movies, and a movie can have many genres. So you would actually take out the `genre_id` from the videos table and create a joins table to connect the videos table to the genres table.

Sweet! Went and made a joins table, thank you for the suggestion!

**Comment by samwalker191** [comment]
**Frontend Routes Comments:**

Looks good.
